version: "3"
services:
    hub:
      image: selenium/hub:4.1.0
    firefox:
      image: selenium/node-firefox:4.1.0
      shm_size: '1gb'
      depends_on:
        - hub
      environment:
        - SE_EVENT_BUS_HOST=hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    login:
      image: egeiper/selenium-testng
      depends_on:
        - firefox
      environment:
        - HUB_HOST=hub
        - MODULE=login.xml
      volumes:
        - ./allure-results:/usr/share/alpineDirectory/allure-results
    navigate:
      image: egeiper/selenium-testng
      depends_on:
        - firefox
      environment:
        - HUB_HOST=hub
        - MODULE=navigate.xml
      volumes:
        - ./allure-results:/usr/share/alpineDirectory/allure-results



